### ISSUE TITLE
Not transforming children

### ISSUE THREAD

**Issue by jakoandersen** [wrakky/react-html-parser#35]
When i give it a HTML string that contains children, those children are not called upon with `transform`.

Suppose i have this:
```html
<div>
    <span class="a"></span>
</div>
<div>
    <span class="b"></span>
    <span class="c"></span>
<div>
```

Transform is only invoked twice, one for each div, an not 5 times, one for each node in the tree.

Is this desired behaviour? If so, could it be supported?

**Comment by wrakky** [comment]
Is [convertNodeToElement](https://github.com/wrakky/react-html-parser#function-convertnodetoelementnode-index-transform) what you want? Using `transform` breaks the conversion chain for the transformed element's children so you need to re-establish it using that function.

**Comment by jakoandersen** [comment]
The problem lies in that the structure is pretty deep, and the elements I want to transform will exist in different depths. I'm also not sure exactly where as the HTML should be dynamic.

Is there not way to skip the break of conversion chain?

**Comment by jakoandersen** [comment]
```js
export const transform = (node, idx) => {
    if (node.type === 'tag' && node.name === 'span') {
        return <MyComponent />;
    }

    return node;
};
```

**Comment by wrakky** [comment]
If you don't return anything (or return `undefined`) from `transform` then processing will carry on as normal. In your example, if the only objective is to return `<MyComponent>` instead of a `<span>` and leave all of the other elements alone then you can remove the `return node` line at the bottom of the function. 

Returning a value from `transform` will break out of default processing and you'll have to manually return `convertNodeToElement` to carry on further down the tree.

**Comment by jakoandersen** [comment]
Yes, that fixed the issue. I had to return `undefined` instead of `node` to let the processing continue down the tree.

Thank you.

PS. It is not very clear in the documentation what those to decisions do.

**Comment by wrakky** [comment]
I'm glad it's sorted! I agree about the docs and it's something I would like to address given the chance - I think most of the information is there but a better layout and making things more obvious with code examples would be a good improvement.
